package frc.lib.helpers;


@SuppressWarnings("unused")
public enum UnitTypes {
    METERS, CENTIMETERS, RADIANS, DEGREES, ROUNDS, PERCENTAGES,
    METERS_PER_SECOND, RADIANS_PER_SECOND, DEGREES_PER_SECOND, ROUNDS_PER_SECOND,
    METERS_PER_SECOND_SQUARED, RADIANS_PER_SECOND_SQUARED, DEGREES_PER_SECOND_SQUARED, ROUNDS_PER_SECOND_SQUARED,
}
